src/platform/StdSchedulerMac.mm

respondsToSelector isn't properly guarding against calling this method on unsupported platforms, possibly because it existed as a private method in OS X before 10.9. For example, attempting to build this on OS X 10.8 fails with the error:
```
no visible @interface for 'NSTimer' declares the selector 'setTolerance:'
```
Since the default tolerance is 0 anyway, this can be removed without adverse effect.

StdSchedulerMac: don't call setTolerance:

---

planet/Objects.ocd/Animals.ocd/PiranhaSmall.ocd/Script.c
planet/Objects.ocd/Animals.ocd/Zaphive.ocd/Zap.ocd/Script.c
planet/Objects.ocd/Items.ocd/Tools.ocd/Axe.ocd/Script.c
planet/Objects.ocd/Items.ocd/Tools.ocd/Pickaxe.ocd/Script.c
planet/Objects.ocd/Items.ocd/Tools.ocd/Sickle.ocd/Script.c
planet/Objects.ocd/Items.ocd/Tools.ocd/WindBag.ocd/Script.c
planet/Objects.ocd/Items.ocd/Weapons.ocd/Club.ocd/Script.c
planet/Objects.ocd/Libraries.ocd/Structures.ocd/Structure.ocd/Script.c
planet/Objects.ocd/Libraries.ocd/Structures.ocd/Vendor.ocd/Script.c
planet/Objects.ocd/Structures.ocd/ChemicalLab.ocd/Script.c
planet/Objects.ocd/Structures.ocd/Elevator.ocd/Case.ocd/Script.c
planet/Objects.ocd/Structures.ocd/Elevator.ocd/Script.c
planet/Objects.ocd/Structures.ocd/Sawmill.ocd/Script.c
planet/Objects.ocd/Structures.ocd/SteamEngine.ocd/Script.c
planet/Objects.ocd/Structures.ocd/WindGenerator.ocd/Script.c
planet/Objects.ocd/Vehicles.ocd/Airship.ocd/Script.c
planet/Objects.ocd/Vehicles.ocd/Lorry.ocd/Script.c
planet/System.ocg/NamedParams.c

Sound() has a lot of optional arguments which can be used independently. Most of the time, only a single one of these is needed, resulting in [oddly-looking code](http://docs.openclonk.org/en/sdk/script/SoundModifiers.html).
With this patch, a proplist can be passed instead, simulating named arguments. This pattern is common in other languages such as Ruby and JavaScript.
I also replaced some usages of Sound() with the new variant.

Use a proplist for optional Sound() arguments

---

src/platform/C4Window.h
src/platform/C4WindowGTK.cpp

The same thing should somehow also be possible using gdk_device_grab(), but I couldn't get it to work properly.
The pure GTK code would look something like this (without focus handling):
```cpp
void C4Window::GrabMouse(bool grab)
{
GdkWindow *gdkwindow = gtk_widget_get_window(GTK_WIDGET(window));
GdkDeviceManager *device_manager = gdk_display_get_device_manager(gdk_display_get_default());
if (!device_manager) return;
GdkDevice *pointer = gdk_device_manager_get_client_pointer(device_manager);
if (grab)
{
gdk_device_grab(pointer, gdkwindow, GDK_OWNERSHIP_NONE, true, GDK_ALL_EVENTS_MASK, NULL, GDK_CURRENT_TIME);
}
else
{
gdk_device_ungrab(pointer, GDK_CURRENT_TIME);
}
}
```
This wouldn't allow you to click outside the window, but the mouse cursor gets stuck when nearing the edge of the game …

Implement mouse grabbing for GTK on X11 (#1637)

---

src/lib/StdCompiler.cpp
src/network/C4Network2Res.cpp

valgrind was complaining about the use of `free` to deallocate memory allocated with `new` rather than `malloc`. Fixed this.

Make memory allocation/deallocation more consistent

---

openclonk.desktop

[Debian bug #825678](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825678) suggested to modify OpenClonk's desktop file to add it to the StrategyGame and ArcadeGame categories to aid discoverability. Strategy sort of fits considering that it contains real-time strategy levels. Arcade seemed borderline but also felt true given that the tutorial and some other levels might be considered arcade.

Add OpenClonk to StrategyGame and ArcadeGame categories.

---

src/script/C4Aul.cpp
src/script/C4Aul.h
src/script/C4AulLink.cpp
src/script/C4PropList.cpp
src/script/C4PropList.h
src/script/C4ScriptHost.cpp
src/script/C4ScriptHost.h

If a local variable in a definition was set to a proplist inside the
Definition() callback, and that proplist contained cyclic references
then those references were leaked. Typically cyclic references for
script-created proplists are broken in
C4PropListScript::ClearScriptPropLists, however definition proplists
are changed to be static proplists in
C4PropList::FreezeAndMakeStaticRecursively.
To fix this, each script host maintains a list of proplists made static
by FreezeAndMakeStaticRecursively, and explicitly deletes all of these
proplists on Clear().
This leak also leads to an assertion failure inside
C4PropListScript::ClearScriptPropLists in debug mode, and can also be
observed by C4PropList::PropLists not being empty after game clear.
The definition in …

Don't leak static proplists with cyclic references

---

src/graphics/C4Shader.h
src/landscape/C4LandscapeRender.cpp
src/landscape/C4LandscapeRender.h

It uses a int32[2]-vector for the realtime because ARB_gpu_shader_fp64 is not very well supported before OpenGL 4.0 on some Intel GPUs.

Share time information (frameCounter and realtime) with landscape shaders

---

CMakeLists.txt

Hi,
Following the discussion last summer [1].
Here are some patches to allow building OpenClonk with Buildroot.
The last patch (add C4GROUP_TOOL_ONLY) is not really nice.
It would be great to be able to just compile c4goup tool without add a lot of complexity in the CMake build system.
This series is based on the stable-8 branch.
I can rebase against master if needed.
[1] https://forum.openclonk.org/topic_show.pl?tid=3391

Stable 8 for upstream

---

src/script/C4Script.cpp
src/script/C4ValueArray.h
tests/aul/AulDeathTest.cpp

SetLength didn't check whether its first parameter was valid, and
attempted to dereference a NULL pointer when passed nil.

Script: Test SetLength parameter 0 for nil (GH #79)

---

tools/default.nix

Now that openclonk gets installed to bin, we don't need to (and
can't!) create the symlink anymore.

nix expression: fix build

---

src/script/C4AulParse.cpp
tests/aul/AulSyntaxTest.cpp

We were misparsing `#warning` pragmas which didn't have all of the required information. We shouldn't do that.

Better warning pragma parsing

---

src/object/C4Movement.cpp
src/object/C4Object.h

This is still not the end, but it is a small step forward :)

Refactor movement: Further cleanup, added new function

---

docs/sdk/script/MapScript.xml
src/landscape/C4MapScript.h
src/landscape/C4MapScriptAlgo.cpp
src/script/C4StringTable.cpp
src/script/C4StringTable.h

Adds a new internal algorithm _C4MapScriptAlgoSetMaterial_ and uses it, when the _Material_ property is used for an algorithm.

Allow Material property for map script algorithms.

---

.travis.yml
CMakeLists.txt

This requires at least CMake 3.9 for GCC and clang and 3.13 for MSVC.
Older versions will still work, but without LTO.
In contrast to the old variant, this now works with clang as well.
@isilkor: Can you check whether this does the right thing with MSVC?

Use CMake's LTO/LTCG/IPO support

---

src/game/C4Viewport.cpp
src/landscape/fow/C4FoW.cpp

See https://bugs.openclonk.org/view.php?id=2065
We need to have a context selected even if we don't draw, because buffer objects and textures may be created, which are just ignored otherwise.
The `EnsureMainContextSelected()` in `C4FoW::~C4FoW` was a bugfix for another bug, but I don't know how it can be reproduced. It's probably also fixed by this commit.
Setting the main context at that point is wrong anyway, because we may have another context already.

Fix bug with incorrect OpenGL context after viewport closing in editor.

---

src/graphics/C4DrawGL.cpp

See https://bugs.openclonk.org/view.php?id=2004
Caused by trying to create shaders with no active context.

Fix crash on closing scenario in editor.

---

src/object/C4Object.cpp
src/object/C4Object.h

See https://bugs.openclonk.org/view.php?id=2048

Fix same object being removed multiple times (#2048)

---

planet/Objects.ocd/Libraries.ocd/AimManager.ocd/Script.c

Actually this branch was intended for luchs suggestion of making the bow auto-add an arrow first, and only start drawing when you press the button. This is not as easy to do and requires some changes in the aim manager (because adding an arrow is part of the drawing animation, and you'd have to split that and track some states in the bow). Doing that would be a separate PR, so I'll just merge the fix first.

Fix ranged weapon aiming

---

cmake/FindPNG.cmake

Homebrew on macOS uses /usr/local/include/libpng16.

Add a guess for the location of libpng headers.

---

CMakeLists.txt

This is a linker flag, not a compiler flag, so move it to
CMAKE_SHARED_LINKER_FLAGS.

Fix a warning related to -headerpad_max_install_names in the macOS build

---

cmake/FindAudio.cmake

Changeset cf474e9 removed one (APPLE OR) clause from FindAudio, but
missed the other one.  They need to match so that the detection logic
is correct.
Alut is required if AUDIO_TK == AUDIO_TK_OPENAL, because it's included
in C4SoundIncludes.h with no platform-specific conditionals.

Fix FindAudio's detection of Alut on macOS

---

CMakeLists.txt

These need to be specified along with GTK3_LIBRARIES /
GTK3_gtksourceview_LIBRARIES, otherwise the libraries will not be found
(if they're on non-system paths).

Fix missing refs to GTK3_LIBRARY_DIRS / GTK3_gtksourceview_LIBRARY_DIRS.

---

src/c4group/C4Group.cpp

In commit 99992b6f47 it seems that the changes were added after the break by accident, resulting in dead code. However, this code did not seem to cause any problems, so I am not sure whether we need this chance

Fix accident in C4Group

---

CMakeLists.txt

This silences a warning from CMake "Policy CMP0071 is not set".

Set the SKIP_AUTOGEN property on mape-resource.c.

---

cmake/DeployQt.cmake

Pass macdeployqt the -no-strip flag when we're using the Debug CMake
configuration and DEPLOY_QT_LIBRARIES=1.  Otherwise, the main app gets
stripped, which defeats the point of a debug build.

Do not strip executables in debug mode when using macdeployqt.

---

.gitignore
.travis.yml
CMakeLists.txt
tests/aul/AulDeathTest.cpp

StdSchedulerMac needs to be included in libmisc so that the netpuncher
and tests targets can pick it up.  This is conditional on APPLE being set
(unlike the other StdScheduler* files) because the Travis builds for other
OSes do not have the Objective C++ compiler installed.  Also, there is an
earlier cset that implies that this was a problem more generally (515aaf6).
Clang/libc++ on macOS apparently doesn't support quick_exit, even with
-std=c++11.  Use a macro check in AulDeathTest to switch it to regular
exit instead.
Add test build output and autogen directories to .gitignore.

Fix build of netpuncher and tests on macOS, and add a Travis macOS build

---

src/script/C4PropList.cpp
src/script/C4PropList.h
src/script/C4Value.h

```js
// Example script
global func Main() {
var x = Bla(1000 * 12);
Log("Done");
}
global func Bla(count) {
if (count < 1)
return nil;
count -= 1;
var x = new Global { i = count };
var a = Bla(count / 2);
var b = Bla(count - count / 2);
x.b = b;
x.a = a;
return x;
}
```
The phenomenon occurs depending on whether the order of creating `a` and `b` is the same as assigning them to `x` or not. On some architectures/compiler/os combinations, the problem may also occur randomly, regardless of the order.
Execution times vary between 15 ms and 700 ms without this patch.

Fix slowness in deleting proplist references

---

src/graphics/C4DrawGLMac.mm
src/platform/C4AppT.cpp
src/platform/C4Window.h
src/platform/C4WindowSDL.cpp
src/platform/C4WindowWin32.cpp

No answer in #137 but whatever. It does fix the issue on my machine.

SDL window init: test availability of AA/subsampling before requiring it
